version: 2.1

orbs:
  env_var_check: eric-hu/delivery-test@dev:env-var-check

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          TEST_VAL: foo

    steps:
      - checkout
      - run: export BAR=$TEST_VAL
      - env_var_check/check_env

