version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node

    steps:
      # Sleep for 10 seconds to allow for streaming testing
      - run: sleep 10
      # Produces >500kb of text
      - run: for i in {1..500000}; do  echo "ping ${i}"; done
      # Sleep for 10 seconds to allow for streaming testing
      - run: sleep 10
      # Produces >500kb of text
      - run: for i in {1..500000}; do  echo "ping ${i}"; done
      # Sleep for 10 seconds to allow for streaming testing
      - run: sleep 10
      # Produces >500kb of text
      - run: for i in {1..500000}; do  echo "ping ${i}"; done
