version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: sleep 2

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only:
                - '/.*/'
