#orbs:
  #dev_test: "eric-hu/delivery-test@1.0.2"

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      #- run: env
      #- dev_test/hello_world
