version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout

workflows:
  test-staging:
    jobs:
      - build:
          name: build-staging
  test-and-deploy-prod:
    jobs:
      - build:
          name: build-prod
