version: 2.1
orbs:
  inline_example:
    jobs:
      my_inline_job:
        parameters:
          parallel:
            type: string
            default: "1"
        machine: true
        parallelism: <<parameters.parallel>>
        steps:
          - run: echo "hi"

workflows:
  build-test-deploy:
    jobs:
      - inline_example/my_inline_job:
          parallel: 2
