version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node

    steps:
      - run: sleep 5
      - run: |
          for dummy in {1...100}; do
            for i in {1..5000}; do
              printf '%*s \n' $i | tr ' ' "#"
            done
            sleep 1
          done && sleep 5
