version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run: exit 1
      - run:
          command: sleep 30
          when: on_fail

workflows:
  version: 2
  btd:
    jobs:
      - build
