version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run:
          command: sleep 10 && exit 1
          background: true
      - run: sleep 15

workflows:
  btd:
    jobs:
      - build
